ASSISTANT_APP_NAME = "newagent-32e9f"
ASSISTANT_OAUTH_SCOPE = (
  'https://www.googleapis.com/auth/assistant-sdk-prototype'
)
PUBSUB_OAUTH_SCOPE = 'https://www.googleapis.com/auth/pubsub'
ASSISTANT_CREDENTIALS_FILENAME = 'assistant_credentials.json'
DEFAULT_GRPC_DEADLINE = 60 * 3 + 5
DEFAULT_AUDIO_SAMPLE_RATE = 16000
DEFAULT_AUDIO_SAMPLE_WIDTH = 2
DEFAULT_AUDIO_ITER_SIZE = 3200
DEFAULT_AUDIO_DEVICE_BLOCK_SIZE = 6400
DEFAULT_AUDIO_DEVICE_FLUSH_SIZE = 25600